In [1]:
# Pandas

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
# 1D data structures in Pandas

In [4]:
# Pandas Series

In [5]:
# A Pandas Series is a one-dimensional labeled array capable of holding 
# any data type (integers, strings, floats, Python objects, etc.).

# Each element has:
# Data (values)
# Label (index)

In [6]:
# Creating a Pandas Series

In [7]:
# 1. From a List

In [8]:
import pandas as pd

In [9]:
s = pd.Series([10, 20, 30])

In [10]:
s

0    10
1    20
2    30
dtype: int64

In [11]:
# 2. With Custom Index

In [12]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

In [13]:
s

a    10
b    20
c    30
dtype: int64

In [14]:
# 3. From a Dictionary

In [15]:
data = {'a': 10, 'b': 20, 'c': 30}
s = pd.Series(data)

In [16]:
s

a    10
b    20
c    30
dtype: int64

In [17]:
# 4. From a Single Value

In [18]:
s = pd.Series(5, index=[0,1,2,3])

In [19]:
s

0    5
1    5
2    5
3    5
dtype: int64

In [20]:
# Important Attributes

In [21]:
s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

In [22]:
s

a    10
b    20
c    30
dtype: int64

In [23]:
s.values   # returns data

array([10, 20, 30])

In [24]:
s.index    # returns index labels

Index(['a', 'b', 'c'], dtype='object')

In [25]:
s.dtype

dtype('int64')

In [26]:
s.shape

(3,)

In [27]:
# Basic Data Manipulation

In [28]:
# 1. Arithmetic Operations

In [29]:
s = pd.Series([1,2,3])
print(s * 2)

0    2
1    4
2    6
dtype: int64

In [30]:
# 2. Handling Missing Values

In [31]:
s = pd.Series([1, None, 3])

In [32]:
s.isnull()

0    False
1     True
2    False
dtype: bool

In [33]:
s.dropna()

0    1.0
2    3.0
dtype: float64

In [34]:
s.fillna(0)

0    1.0
1    0.0
2    3.0
dtype: float64

In [35]:
# Value Counts

In [36]:
s = pd.Series([1,2,2,3,3,3])

In [37]:
s.value_counts()

3    3
2    2
1    1
Name: count, dtype: int64

In [38]:
# Indexing

In [39]:
s = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])

In [40]:
s

a    10
b    20
c    30
d    40
dtype: int64

In [41]:
# Indexing by Label

In [42]:
s['a']

np.int64(10)

In [43]:
# 2D data structures in Pandas

In [44]:
data = {
    "Customer_ID": [101, 102, 103, 104, 105],
    "Name": ["Snehal", "Tanishka", "Savi", "Sanika", "Rani"],
    "Age": [18, 25, None, 20, 30],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai"],
    "Salary": [50000, 60000, 55000, None, 65000]
}

In [45]:
df = pd.DataFrame(data)

In [46]:
print(df)

   Customer_ID      Name   Age    City   Salary
0          101    Snehal  18.0    Pune  50000.0
1          102  Tanishka  25.0  Mumbai  60000.0
2          103      Savi   NaN    Pune  55000.0
3          104    Sanika  20.0   Delhi      NaN
4          105      Rani  30.0  Mumbai  65000.0

In [47]:
# Convert DataFrame to CSV

In [48]:
df.to_csv("customer_data.csv", index=False)

In [49]:
# Load Dataset from CSV

In [50]:
df = pd.read_csv("customer_data.csv")

In [51]:
df

   Customer_ID      Name   Age    City   Salary
0          101    Snehal  18.0    Pune  50000.0
1          102  Tanishka  25.0  Mumbai  60000.0
2          103      Savi   NaN    Pune  55000.0
3          104    Sanika  20.0   Delhi      NaN
4          105      Rani  30.0  Mumbai  65000.0

In [52]:
# Data Understanding (EDA)

In [53]:
df.head()

   Customer_ID      Name   Age    City   Salary
0          101    Snehal  18.0    Pune  50000.0
1          102  Tanishka  25.0  Mumbai  60000.0
2          103      Savi   NaN    Pune  55000.0
3          104    Sanika  20.0   Delhi      NaN
4          105      Rani  30.0  Mumbai  65000.0

In [54]:
df.tail()

   Customer_ID      Name   Age    City   Salary
0          101    Snehal  18.0    Pune  50000.0
1          102  Tanishka  25.0  Mumbai  60000.0
2          103      Savi   NaN    Pune  55000.0
3          104    Sanika  20.0   Delhi      NaN
4          105      Rani  30.0  Mumbai  65000.0

In [55]:
df.shape

(5, 5)

In [56]:
df.columns

Index(['Customer_ID', 'Name', 'Age', 'City', 'Salary'], dtype='object')

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Customer_ID  5 non-null      int64
 1   Name         5 non-null      object
 2   Age          4 non-null      float64
 3   City         5 non-null      object
 4   Salary       4 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 332.0+ bytes

In [58]:
df.describe()

       Customer_ID        Age        Salary
count     5.000000   4.000000      4.000000
mean    103.000000  23.250000  57500.000000
std       1.581139   5.377422   6454.972244
min     101.000000  18.000000  50000.000000
25%     102.000000  19.500000  53750.000000
50%     103.000000  22.500000  57500.000000
75%     104.000000  26.250000  61250.000000
max     105.000000  30.000000  65000.000000

In [59]:
# Handling Missing Values

In [60]:
df.isnull().sum()

Customer_ID    0
Name           0
Age            1
City           0
Salary         1
dtype: int64

In [61]:
# Fill missing values

In [62]:
# Fill Age with mean

In [63]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [64]:
df

   Customer_ID      Name    Age    City   Salary
0          101    Snehal  18.00    Pune  50000.0
1          102  Tanishka  25.00  Mumbai  60000.0
2          103      Savi  23.25    Pune  55000.0
3          104    Sanika  20.00   Delhi      NaN
4          105      Rani  30.00  Mumbai  65000.0

In [65]:
# Fill Salary with median

In [66]:
df["Salary"] = df["Salary"].fillna(df["Salary"].median())

In [67]:
# Data Cleaning

In [68]:
df = df.drop_duplicates()

In [69]:
df.rename(columns={"Name": "Customer_Name"}, inplace=True)

In [70]:
df

   Customer_ID Customer_Name    Age    City   Salary
0          101        Snehal  18.00    Pune  50000.0
1          102      Tanishka  25.00  Mumbai  60000.0
2          103          Savi  23.25    Pune  55000.0
3          104        Sanika  20.00   Delhi  57500.0
4          105          Rani  30.00  Mumbai  65000.0

In [71]:
# Change datatype

In [72]:
df["Age"] = df["Age"].astype(int)

In [73]:
# Filtering Data

In [74]:
# Customers with Salary > 55000

In [75]:
high_salary = df[df["Salary"] > 55000]
print(high_salary)

   Customer_ID Customer_Name  Age    City   Salary
1          102      Tanishka   25  Mumbai  60000.0
3          104        Sanika   20   Delhi  57500.0
4          105          Rani   30  Mumbai  65000.0

In [76]:
# Selecting Data

In [77]:
# Single column

In [78]:
print(df["Customer_Name"])

0      Snehal
1    Tanishka
2        Savi
3      Sanika
4        Rani
Name: Customer_Name, dtype: object

In [79]:
# Multiple columns

In [80]:
print(df[["Customer_Name", "Salary"]])

  Customer_Name   Salary
0        Snehal  50000.0
1      Tanishka  60000.0
2          Savi  55000.0
3        Sanika  57500.0
4          Rani  65000.0

In [81]:
# Row selection

In [82]:
print(df.iloc[0])  # first row

Customer_ID          101
Customer_Name     Snehal
Age                   18
City                Pune
Salary           50000.0
Name: 0, dtype: object

In [83]:
# Sorting Data

In [84]:
df = df.sort_values(by="Salary", ascending=False)

In [85]:
df

   Customer_ID Customer_Name  Age    City   Salary
4          105          Rani   30  Mumbai  65000.0
1          102      Tanishka   25  Mumbai  60000.0
3          104        Sanika   20   Delhi  57500.0
2          103          Savi   23    Pune  55000.0
0          101        Snehal   18    Pune  50000.0

In [86]:
# Merge Data

In [87]:
df1 = pd.DataFrame({
    "Customer_ID": [101, 102],
    "Product": ["Car", "Bike"]
})

In [88]:
merged = pd.merge(df, df1, on="Customer_ID", how="left")

In [89]:
merged

   Customer_ID Customer_Name  Age    City   Salary Product
0          105          Rani   30  Mumbai  65000.0     NaN
1          102      Tanishka   25  Mumbai  60000.0    Bike
2          104        Sanika   20   Delhi  57500.0     NaN
3          103          Savi   23    Pune  55000.0     NaN
4          101        Snehal   18    Pune  50000.0     Car